[build]
  command = "npm run build"  # The build command for your project
  publish = "build"         # The directory to publish (output of the build process)

[[redirects]]
  from = "/*"              # Redirect all paths
  to = "/index.html"       # Redirect to the index.html file (for client-side routing)
  status = 200             # Set the HTTP status code for the redirect
